<?php

namespace App\Model;

use Nette;
use Tulinkry;

class RepertoirModel extends Tulinkry\Model\BaseModel
{
	private $songs;

	public function __construct ()
	{
        $this -> songs = array (
            (object) [
                "name" => "S' Wonderful",
                "interpreter" => "George Gershwin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EDxrKlQPZ2M",
                "tags" => [],
            ],
            (object) [
                "name" => "Big Swing Face",
                "interpreter" => "William O. Potts",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=I2qYyjtlPBg",
                "tags" => [],
            ],
            (object) [
                "name" => "Wonderwall",
                "interpreter" => "N. Gallagher",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rCI27zi30nc",
                "tags" => [],
            ],
            (object) [
                "name" => "Hello dolly",
                "interpreter" => "Jerry Herman",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6Tnfi49zJ_k",
                "tags" => [],
            ],
            (object) [
                "name" => "Haven't Met You Yet",
                "interpreter" => "Michael Bublé",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1AJmKkU5POA",
                "tags" => [],
            ],
            (object) [
                "name" => "A String Of Pearls",
                "interpreter" => "Jerry Gray",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rznsWgym9gc",
                "tags" => [ "big band", "jazz" ],
            ],
            (object) [
                "name" => "Lásko má já stůňu",
                "interpreter" => "Karel Svoboda",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EJlY1M65Xao",
                "tags" => [],
            ],
            (object) [
                "name" => "Přejdi Jordán",
                "interpreter" => "Zdeněk Marat",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=D6Jn8OLVuW8",
                "tags" => [],
            ],
            (object) [
                "name" => "Kočka není pes",
                "interpreter" => "Elvis Presley",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=GaKo95U4RU8",
                "tags" => [],
            ],
            (object) [
                "name" => "Mona Lisa",
                "interpreter" => "Jay Livingston",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=th-QbzRyMIE",
                "tags" => [],
            ],
            (object) [
                "name" => "Je t'aime",
                "interpreter" => "Lara Fabian",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=bVvkcaY5khc",
                "tags" => [],
            ],
            (object) [
                "name" => "Sway",
                "interpreter" => "P. B. Ruiz",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zmYMkl1Grzc",
                "tags" => [],
            ],
            (object) [
                "name" => "Lullaby Of Birdland",
                "interpreter" => "George Shearing",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=XH_lKzuJ0sA",
                "tags" => [],
            ],
            (object) [
                "name" => "Little Secret",
                "interpreter" => "Nikky Yanofsky",
                "visible" => true,
                "link" => "https://youtu.be/AFl9SwnItj0?t=1m26s",
                "tags" => [],
            ],
            (object) [
                "name" => "Waterloo",
                "interpreter" => "Benny Anderson",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Sj_9CiNkkn4",
                "tags" => [],
            ],
            (object) [
                "name" => "Mack The Knife",
                "interpreter" => "Kurt Weil",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SEllHMWkXEU",
                "tags" => [],
            ],
            (object) [
                "name" => "I Dreamed A Dream",
                "interpreter" => "C. M. Schönberg",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=-p6OH7FoWoQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Chain Of Fools",
                "interpreter" => "Aretha Franklin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gGAiW5dOnKo",
                "tags" => [],
            ],
            (object) [
                "name" => "Goldeneye",
                "interpreter" => "John Barry",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=v5e3H038u2Q",
                "tags" => [],
            ],
            (object) [
                "name" => "Trombonové zazvonění",
                "interpreter" => "Pavel Rabas",
                "visible" => true,
                "link" => NULL,
                "tags" => [],
            ],
            (object) [
                "name" => "One Moment In Time",
                "interpreter" => "Albert Hammond",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=96aAx0kxVSA",
                "tags" => [],
            ],
            (object) [
                "name" => "Can't Take My Eyes Off You",
                "interpreter" => "Bob Crewe",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=LmiOSaGiEes",
                "tags" => [],
            ],
            (object) [
                "name" => "The Best",
                "interpreter" => "Mike Chapman",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mNU3aIJs88g",
                "tags" => [],
            ],
            (object) [
                "name" => "Thank You For The Music",
                "interpreter" => "Benny Anderson",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=0dcbw4IEY5w",
                "tags" => [],
            ],
            (object) [
                "name" => "I Feel Good",
                "interpreter" => "James Brown",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=U5TqIdff_DQ",
                "tags" => [],
            ],
            (object) [
                "name" => "In The Mood",
                "interpreter" => "Joe Garland",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=_CI-0E_jses",
                "tags" => [],
            ],
            (object) [
                "name" => "Až se k tobě vrátím",
                "interpreter" => "Kryštof Marek",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=5eZxx4c9OeU",
                "tags" => [],
            ],
            (object) [
                "name" => "Hallelujah",
                "interpreter" => "Leonard Cohen",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ttEMYvpoR-k",
                "tags" => [],
            ],
            (object) [
                "name" => "Pátá",
                "interpreter" => "T. Hatch",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=226hdv0lvOw",
                "tags" => [],
            ],
            (object) [
                "name" => "Hernando's Hideway",
                "interpreter" => "Richard Adler",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=NzOoRZODdCY",
                "tags" => [],
            ],
            (object) [
                "name" => "I Just Called",
                "interpreter" => "Stevie Wonder",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1bGOgY1CmiU",
                "tags" => [],
            ],
            (object) [
                "name" => "Mr. Bojangles",
                "interpreter" => "Jery Jeff Wolker",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Zif1W8fxEJU",
                "tags" => [],
            ],
            (object) [
                "name" => "You'll Never Find Another Love Like Mine",
                "interpreter" => "Knenneth Gamble",
                "visible" => true,
                "link" => "https://youtu.be/nKt7kElWKic?t=25s",
                "tags" => [],
            ],
            (object) [
                "name" => "Sex Bomb",
                "interpreter" => "Tom Jones",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wgDSx-mkxKI",
                "tags" => [],
            ],
            (object) [
                "name" => "Things",
                "interpreter" => "Bobby Darin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6gh8LXvgVQk",
                "tags" => [],
            ],
            (object) [
                "name" => "Crazy Little Thing Called Love",
                "interpreter" => "Freddie Mercury",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zO6D_BAuYCI",
                "tags" => [],
            ],
            (object) [
                "name" => "My Heart Will Go On",
                "interpreter" => "James Horner",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=FHG2oizTlpY",
                "tags" => [],
            ],
            (object) [
                "name" => "Bad, Bad Leroy Brown",
                "interpreter" => "Jim Croce",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=QvwDohEEQ1E",
                "tags" => [],
            ],
            (object) [
                "name" => "Směs písní Karla Hašlera",
                "interpreter" => "Karel Hašler",
                "visible" => true,
                "link" => NULL,
                "tags" => [],
            ],
            (object) [
                "name" => "Já, Máří Magdaléna",
                "interpreter" => "A. L. Webber",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=E5AFECPbscw",
                "tags" => [],
            ],
            (object) [
                "name" => "Skyfall",
                "interpreter" => "Paul Epworth",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=DeumyOzKqgI",
                "tags" => [],
            ],
            (object) [
                "name" => "Škoda lásky",
                "interpreter" => "Jaromír Vejvoda",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=jyI9Pj4CEdE",
                "tags" => [],
            ],
            (object) [
                "name" => "Rock Around The Clock",
                "interpreter" => "M. C. Freedman",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZgdufzXvjqw",
                "tags" => [],
            ],
            (object) [
                "name" => "The Winner Takes It All",
                "interpreter" => "Benny Anderson",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=92cwKCU8Z5c",
                "tags" => [],
            ],
            (object) [
                "name" => "James Bond Theme",
                "interpreter" => "Monty Norman",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6ebAssCr990",
                "tags" => [],
            ],
            (object) [
                "name" => "It Don't Mean A Thing",
                "interpreter" => "Duke Ellington",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=qDQpZT3GhDg",
                "tags" => [],
            ],
            (object) [
                "name" => "Close Your Eyes",
                "interpreter" => "Michael Bublé",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=LoEWmc60wJY",
                "tags" => [],
            ],
            (object) [
                "name" => "Jingle Bells",
                "interpreter" => "James L. Pierpont",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=F5zRx1CfZ3Y",
                "tags" => [],
            ],
            (object) [
                "name" => "Tell Him",
                "interpreter" => "David Foster",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=MyPu3SUDw94",
                "tags" => [],
            ],
            (object) [
                "name" => "Byla jedna holčička",
                "interpreter" => "Moe Jaffe",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=22IcgPwXFQE",
                "tags" => [],
            ],
            (object) [
                "name" => "Away In A Manger",
                "interpreter" => "American melody",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=HuF-D7eaars",
                "tags" => [],
            ],
            (object) [
                "name" => "Rockin' Around The Christmas Tree",
                "interpreter" => "Johny Marks",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=_6xNuUEnh2g",
                "tags" => [],
            ],
            (object) [
                "name" => "Everyday",
                "interpreter" => "Slade",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1pPL9PPy1MI",
                "tags" => [],
            ],
            (object) [
                "name" => "Směs Pomáda",
                "interpreter" => "Jim Jacobs",
                "visible" => true,
                "link" => NULL,
                "tags" => [],
            ],
            (object) [
                "name" => "Tichá noc",
                "interpreter" => "Franz Gruber",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6YK0qvh4ym8",
                "tags" => [],
            ],
            (object) [
                "name" => "Četník se žení",
                "interpreter" => "Raymond Lefevre",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=AvKCn3WImgo",
                "tags" => [],
            ],
            (object) [
                "name" => "Birdland",
                "interpreter" => "Joe Zawinul",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wsWViUTJ_0c",
                "tags" => [],
            ],
            (object) [
                "name" => "Sir Duke",
                "interpreter" => "Stevie Wonder",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6sIjSNTS7Fs",
                "tags" => [],
            ],
            (object) [
                "name" => "Psát od prvních řádků",
                "interpreter" => "A. L. Webber",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=uf35-Q74tdQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Slunečníce",
                "interpreter" => "Eman Nováček",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=G6JQhz_deWU",
                "tags" => [],
            ],
            (object) [
                "name" => "Žabák",
                "interpreter" => "Václav Trojan",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZkGFqW7iZIQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Smíření",
                "interpreter" => "Petr Ulrych",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gbigns3JDOI",
                "tags" => [],
            ],
            (object) [
                "name" => "Padam, Padam",
                "interpreter" => "Henry Contet",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Kya3c4WJZAk",
                "tags" => [],
            ],
            (object) [
                "name" => "Milord",
                "interpreter" => "Georges Moustaki",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=vwe3CzWZ4Bg",
                "tags" => [],
            ],
            (object) [
                "name" => "Non Je Ne Regrette Rien",
                "interpreter" => "Charles Dumont",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Q3Kvu6Kgp88",
                "tags" => [],
            ],
            (object) [
                "name" => "Čardáš swing",
                "interpreter" => "Ferdinand Havlík",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=7motL4NlTZ8",
                "tags" => [],
            ],
            (object) [
                "name" => "New York",
                "interpreter" => "John Kander",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EUrUfJW1JGk",
                "tags" => [],
            ],
            (object) [
                "name" => "Dneska pojedem vlakem ven",
                "interpreter" => "Havrani",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=TjUl1LO1zWk",
                "tags" => [],
            ],
            (object) [
                "name" => "Sing, Sing, Sing",
                "interpreter" => "Louis Prima",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=fhyhP_5VfKM",
                "tags" => [],
            ],
            (object) [
                "name" => "Everything",
                "interpreter" => "Michael Bublé",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SPUJIbXN0WY",
                "tags" => [],
            ],
            (object) [
                "name" => "Feeling Good",
                "interpreter" => "L. Bricusse",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Edwsf-8F3sI",
                "tags" => [],
            ],
            (object) [
                "name" => "Tiger Rag",
                "interpreter" => "La Rocca",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rqo-AuSFaQg",
                "tags" => [],
            ],
            (object) [
                "name" => "Summertime",
                "interpreter" => "George Gershwin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=XivELBdxVRM",
                "tags" => [],
            ],
            (object) [
                "name" => "It Had Better Be Tonight",
                "interpreter" => "Henry Manchini",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=p6KsEY0NIkE",
                "tags" => [],
            ],
            (object) [
                "name" => "All I Want For Christmas Is You",
                "interpreter" => "Mariah Carey",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=yXQViqx6GMY",
                "tags" => [ "dance/pop", "R & B", "christmas" ],
            ],
            (object) [
                "name" => "Jen jedenkrát v roce",
                "interpreter" => "Jiří Zmožek",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=-Fxj_4x4x2E",
                "tags" => [],
            ],
            (object) [
                "name" => "Každý má svůj sen",
                "interpreter" => "A. L. Webber",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SZtgPBXkOCs",
                "tags" => [],
            ],
            (object) [
                "name" => "Yakety Sax",
                "interpreter" => "Benny Hill",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZnHmskwqCCQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Hluboko, hluboko",
                "interpreter" => "Bert Kaempfert",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=4Wh7fvg_W8Q",
                "tags" => [],
            ],
            (object) [
                "name" => "Už nikdy víc milovat nebudu",
                "interpreter" => "Karel Hála",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wragKkh75K8",
                "tags" => [],
            ],
            (object) [
                "name" => "Vím, že jsi se mnou",
                "interpreter" => "Karel Svoboda",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=j4GyDhIPd0I",
                "tags" => [],
            ],
            (object) [
                "name" => "Hádej Matyldo",
                "interpreter" => "Australská lidová",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=K8ConPKzAeo",
                "tags" => [],
            ],
            (object) [
                "name" => "White Christmas",
                "interpreter" => "Michael Bublé",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=8OsgqpnuizY",
                "tags" => [],
            ],
            (object) [
                "name" => "You Needed Me",
                "interpreter" => "Randy Goodrum",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=IZNBjY7F4EM",
                "tags" => [],
            ],
            (object) [
                "name" => "Save The Last Dance For Me",
                "interpreter" => "Mort Shuman",
                "visible" => true,
                "link" => "https://youtu.be/LAjfB0XfjkA?t=9s",
                "tags" => [],
            ],
            (object) [
                "name" => "Bei mir bist du schön",
                "interpreter" => "Sholom Sekunda",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gQHXR8h4woQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Memory",
                "interpreter" => "A. L. Webber",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=4-L6rEm0rnY",
                "tags" => [],
            ],
            (object) [
                "name" => "Tequila",
                "interpreter" => "Chuck Rio",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zkNsspRhIGE",
                "tags" => [],
            ],
            (object) [
                "name" => "My Way",
                "interpreter" => "Paul Anka",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=uP_tMa7VliY",
                "tags" => [],
            ],
            (object) [
                "name" => "Over The Rainbow",
                "interpreter" => "Harold Arlen",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rectLMhmkz8",
                "tags" => [],
            ],
            (object) [
                "name" => "Etuda v E",
                "interpreter" => "F. Chopin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EmQBFLJAIcY",
                "tags" => [],
            ],
            (object) [
                "name" => "Alexander's Ragtime Band",
                "interpreter" => "Irving Berlin",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=qPTbgvzgMZU",
                "tags" => [ "jazz", "ragtime" ],
            ],
            (object) [
                "name" => "Rock This Town",
                "interpreter" => "Brian Setzer",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mvs9ODIjhiU",
                "tags" => [],
            ],
            (object) [
                "name" => "Yesterday",
                "interpreter" => "Paul McCartney",
                "visible" => true,
                "link" => "https://youtu.be/piBiR4vOBm0?t=18s",
                "tags" => [],
            ],
            (object) [
                "name" => "Strangers In The Night",
                "interpreter" => "Frank Sinatra",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=hlSbSKNk9f0",
                "tags" => [],
            ],
            (object) [
                "name" => "Blues Machine",
                "interpreter" => "Michael Sweeney",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=F7bqncyxrzA",
                "tags" => [],
            ],
            (object) [
                "name" => "Thunderball",
                "interpreter" => "John Barry",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=xAQ-nG0AlSg",
                "tags" => [],
            ],
            (object) [
                "name" => "Tenkrát na západě",
                "interpreter" => "Enrico Morricone",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rJDVJy260yQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Beatles Hits",
                "interpreter" => "John Lennon",
                "visible" => true,
                "link" => NULL,
                "tags" => [],
            ],
            (object) [
                "name" => "Let It Snow",
                "interpreter" => "Jule Styne",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mN7LW0Y00kE",
                "tags" => [],
            ],
            (object) [
                "name" => "Monday Monday",
                "interpreter" => "John Phillips",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=h81Ojd3d2rY",
                "tags" => [],
            ],
            (object) [
                "name" => "Funiculi Funicula",
                "interpreter" => "Luigi Denza",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Guh_65i8jZk",
                "tags" => [],
            ],
 
 
            (object) [
                "name" => "Jazz Merry Christmas",
                "interpreter" => "Paul Cook",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=CHTWL-7yD6w",
                "tags" => [],
            ],
            (object) [
                "name" => "Somewhere",
                "interpreter" => "Leonard Bernstein",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=0gIoTnBlh2Q",
                "tags" => [],
            ],
            (object) [
                "name" => "Četník ze Saint Tropez",
                "interpreter" => "Raymond Lefevre",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=sr5iqbGBLVM",
                "tags" => [],
            ],
            (object) [
                "name" => "Četník v New Yorku",
                "interpreter" => "Raymond Lefevre",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=chDjya8jDEU",
                "tags" => [],
            ],
 
            (object) [
                "name" => "Třešňové květy",
                "interpreter" => "Perez Prado",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ta6n8C2ea2Y",
                "tags" => [],
            ],
            (object) [
                "name" => "What A Wonderful World",
                "interpreter" => "Frank Sinatra",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=A3yCcXgbKrE",
                "tags" => [],
            ],
            (object) [
                "name" => "Švihák Lázeňský",
                "interpreter" => "Václav Zahradník",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=RcIe26APRRQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Saxana",
                "interpreter" => "Angela Michaljov",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=cFAykQakqtQ",
                "tags" => [],
            ],
            (object) [
                "name" => "Oh Happy Day",
                "interpreter" => "Gospel",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=FpUVF1MAkNc",
                "tags" => [],
            ],
            (object) [
                "name" => "Turecký pochod",
                "interpreter" => "W. A. Mozart",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=DphG2Lr5cSA",
                "tags" => [],
            ],
            (object) [
                "name" => "Oh, Baby, Baby",
                "interpreter" => "Golden Kids",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=kIpOe7AHURI",
                "tags" => [],
            ],
            (object) [
                "name" => "True Love",
                "interpreter" => "Cole Porter",
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=8bKr_XE0MsA",
                "tags" => [],
            ],
        );
    }


	public function all ( $order = [] )
	{
		uasort($this->songs, function($a, $b) {
			return Nette\Utils\Strings::toAscii($a->name) > Nette\Utils\Strings::toAscii($b->name);
		});
		return $this->songs;
	}

	public function by ( $by = array (), $order = array () )
	{
		$order = array_keys($order)[0];
		uasort($this->songs, function($a, $b) use ($order) {
			return Nette\Utils\Strings::toAscii($a->$order) > Nette\Utils\Strings::toAscii($b->$order);
		});
		return $this->songs;
	}

};