<?php

namespace App\Model;

use Nette;
use Tulinkry;

class RepertoirModel extends Tulinkry\Model\BaseModel
{
	private $songs;

	public function __construct ()
	{
		$this -> songs = array (
            (object) [
                "name" => "S' Wonderful",
                "interpreter" => "George Gershwin",
                "duration" => Nette\Utils\DateTime::from ( "00:03:10" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EDxrKlQPZ2M",
            ],
            (object) [
                "name" => "Big Swing Face",
                "interpreter" => "William O. Potts",
                "duration" => Nette\Utils\DateTime::from ( "00:04:15" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=I2qYyjtlPBg",
            ],
            (object) [
                "name" => "Wonderwall",
                "interpreter" => "N. Gallagher",
                "duration" => Nette\Utils\DateTime::from ( "00:02:44" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rCI27zi30nc",
            ],
            (object) [
                "name" => "Hello dolly",
                "interpreter" => "Jerry Herman",
                "duration" => Nette\Utils\DateTime::from ( "00:02:25" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6Tnfi49zJ_k",
            ],
            (object) [
                "name" => "Haven't Met You Yet",
                "interpreter" => "Michael Bublé",
                "duration" => Nette\Utils\DateTime::from ( "00:03:58" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1AJmKkU5POA",
            ],
            (object) [
                "name" => "A String Of Pearls",
                "interpreter" => "Jerry Gray",
                "duration" => Nette\Utils\DateTime::from ( "00:02:18" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rznsWgym9gc",
            ],
            (object) [
                "name" => "Lásko má já stůňu",
                "interpreter" => "Karel Svoboda",
                "duration" => Nette\Utils\DateTime::from ( "00:02:00" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EJlY1M65Xao",
            ],
            (object) [
                "name" => "Přejdi Jordán",
                "interpreter" => "Zdeněk Marat",
                "duration" => Nette\Utils\DateTime::from ( "00:03:06" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=D6Jn8OLVuW8",
            ],
            (object) [
                "name" => "Kočka není pes",
                "interpreter" => "Elvis Presley",
                "duration" => Nette\Utils\DateTime::from ( "00:02:00" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=GaKo95U4RU8",
            ],
            (object) [
                "name" => "Mona Lisa",
                "interpreter" => "Jay Livingston",
                "duration" => Nette\Utils\DateTime::from ( "00:02:12" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=th-QbzRyMIE",
            ],
            (object) [
                "name" => "Je Taime",
                "interpreter" => "Lara Fabian",
                "duration" => Nette\Utils\DateTime::from ( "00:04:20" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=bVvkcaY5khc",
            ],
            (object) [
                "name" => "Sway",
                "interpreter" => "P. B. Ruiz",
                "duration" => Nette\Utils\DateTime::from ( "00:02:50" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zmYMkl1Grzc",
            ],
            (object) [
                "name" => "Lullaby Of Birdland",
                "interpreter" => "George Shearing",
                "duration" => Nette\Utils\DateTime::from ( "00:02:40" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=XH_lKzuJ0sA",
            ],
            (object) [
                "name" => "Little Secret",
                "interpreter" => "Nikky Yanofsky",
                "duration" => Nette\Utils\DateTime::from ( "00:03:15" ),
                "visible" => true,
                "link" => "https://youtu.be/AFl9SwnItj0?t=1m26s",
            ],
            (object) [
                "name" => "Waterloo",
                "interpreter" => "Benny Anderson",
                "duration" => Nette\Utils\DateTime::from ( "00:02:50" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Sj_9CiNkkn4",
            ],
            (object) [
                "name" => "Mack The Knife",
                "interpreter" => "Kurt Weil",
                "duration" => Nette\Utils\DateTime::from ( "00:02:50" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SEllHMWkXEU",
            ],
            (object) [
                "name" => "I Dreamed A Dream",
                "interpreter" => "C. M. Schönberg",
                "duration" => Nette\Utils\DateTime::from ( "00:04:07" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=-p6OH7FoWoQ",
            ],
            (object) [
                "name" => "Chain Of Fools",
                "interpreter" => "Anretha Franklin",
                "duration" => Nette\Utils\DateTime::from ( "00:03:05" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gGAiW5dOnKo",
            ],
            (object) [
                "name" => "Goldeneye",
                "interpreter" => "John Barry",
                "duration" => Nette\Utils\DateTime::from ( "00:04:30" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=v5e3H038u2Q",
            ],
            (object) [
                "name" => "Trombonové zazvonění",
                "interpreter" => "Pavel Rabas",
                "duration" => Nette\Utils\DateTime::from ( "00:03:00" ),
                "visible" => true,
                "link" => NULL,
            ],
            (object) [
                "name" => "One Moment In Time",
                "interpreter" => "Albert Hammond",
                "duration" => Nette\Utils\DateTime::from ( "00:04:35" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=96aAx0kxVSA",
            ],
            (object) [
                "name" => "Can't Take My Eyes Off You",
                "interpreter" => "Bob Crewe",
                "duration" => Nette\Utils\DateTime::from ( "00:04:00" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=LmiOSaGiEes",
            ],
            (object) [
                "name" => "The Best",
                "interpreter" => "Mike Chapman",
                "duration" => Nette\Utils\DateTime::from ( "00:03:00" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mNU3aIJs88g",
            ],
            (object) [
                "name" => "Thank You For The Music",
                "interpreter" => "Benny Anderson",
                "duration" => Nette\Utils\DateTime::from ( "00:03:50" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=0dcbw4IEY5w",
            ],
            (object) [
                "name" => "I Feel Good",
                "interpreter" => "James Brown",
                "duration" => Nette\Utils\DateTime::from ( "00:03:05" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=U5TqIdff_DQ",
            ],
            (object) [
                "name" => "In The Mood",
                "interpreter" => "Joe Garland",
                "duration" => Nette\Utils\DateTime::from ( "00:03:45" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=_CI-0E_jses",
            ],
            (object) [
                "name" => "Až se k tobě vrátím",
                "interpreter" => "Kryštof Marek",
                "duration" => Nette\Utils\DateTime::from ( "00:03:00" ),
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=5eZxx4c9OeU",
            ],
            (object) [
                "name" => "Hallelujah",
                "interpreter" => "Leonard Cohen",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ttEMYvpoR-k",
            ],
            (object) [
                "name" => "Pátá",
                "interpreter" => "T. Hatch",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=226hdv0lvOw",
            ],
            (object) [
                "name" => "Hernando's Hideway",
                "interpreter" => "Richard Adler",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=NzOoRZODdCY",
            ],
            (object) [
                "name" => "I Just Called",
                "interpreter" => "Stevie Wonder",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1bGOgY1CmiU",
            ],
            (object) [
                "name" => "Mr. Bojangles",
                "interpreter" => "Jery Jeff Wolker",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Zif1W8fxEJU",
            ],
            (object) [
                "name" => "You'll Never Find Another Love Like Mine",
                "interpreter" => "Knenneth Gamble",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://youtu.be/nKt7kElWKic?t=25s",
            ],
            (object) [
                "name" => "Sex Bomb",
                "interpreter" => "Tom Jones",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wgDSx-mkxKI",
            ],
            (object) [
                "name" => "Things",
                "interpreter" => "Bobby Darin",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6gh8LXvgVQk",
            ],
            (object) [
                "name" => "Crazy Little Thing Called Love",
                "interpreter" => "Freddie Mercury",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zO6D_BAuYCI",
            ],
            (object) [
                "name" => "My Heart Will Go On",
                "interpreter" => "James Horner",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=FHG2oizTlpY",
            ],
            (object) [
                "name" => "Bad, Bad Leroy Brown",
                "interpreter" => "Jim Croce",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=QvwDohEEQ1E",
            ],
            (object) [
                "name" => "Směs písní Karla Hašlera",
                "interpreter" => "Karel Hašler",
                "duration" => NULL,
                "visible" => true,
                "link" => NULL,
            ],
            (object) [
                "name" => "Já, Máří Magdaléna",
                "interpreter" => "A. L. Webber",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=E5AFECPbscw",
            ],
            (object) [
                "name" => "Skyfall",
                "interpreter" => "Paul Epworth",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=DeumyOzKqgI",
            ],
            (object) [
                "name" => "Škoda lásky",
                "interpreter" => "Jaromír Vejvoda",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=jyI9Pj4CEdE",
            ],
            (object) [
                "name" => "Rock Around The Clock",
                "interpreter" => "M. C. Freedman",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZgdufzXvjqw",
            ],
            (object) [
                "name" => "The Winner Takes It All",
                "interpreter" => "Benny Anderson",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=92cwKCU8Z5c",
            ],
            (object) [
                "name" => "James Bond Theme",
                "interpreter" => "Monty Norman",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6ebAssCr990",
            ],
            (object) [
                "name" => "It Don't Mean A Thing",
                "interpreter" => "Duke Ellington",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=qDQpZT3GhDg",
            ],
            (object) [
                "name" => "Close Your Eyes",
                "interpreter" => "Michael Bublé",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=LoEWmc60wJY",
            ],
            (object) [
                "name" => "Jingle Bells",
                "interpreter" => "James L. Pierpont",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=F5zRx1CfZ3Y",
            ],
            (object) [
                "name" => "Tell Him",
                "interpreter" => "David Foster",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=MyPu3SUDw94",
            ],
            (object) [
                "name" => "Byla jedna holčička",
                "interpreter" => "Moe Jaffe",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=22IcgPwXFQE",
            ],
            (object) [
                "name" => "Away In A Manger",
                "interpreter" => "American melody",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=HuF-D7eaars",
            ],
            (object) [
                "name" => "Rockin' Around The Christmas Tree",
                "interpreter" => "Johny Marks",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=_6xNuUEnh2g",
            ],
            (object) [
                "name" => "Everyday",
                "interpreter" => "Slade",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=1pPL9PPy1MI",
            ],
            (object) [
                "name" => "Směs Pomáda",
                "interpreter" => "Jim Jacobs",
                "duration" => NULL,
                "visible" => true,
                "link" => NULL,
            ],
            (object) [
                "name" => "Tichá noc",
                "interpreter" => "Franz Gruber",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6YK0qvh4ym8",
            ],
            (object) [
                "name" => "Četník se žení",
                "interpreter" => "Raymond Lefevre",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=AvKCn3WImgo",
            ],
            (object) [
                "name" => "Birdland",
                "interpreter" => "Joe Zawinul",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wsWViUTJ_0c",
            ],
            (object) [
                "name" => "Sir Duke",
                "interpreter" => "Stevie Wonder",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=6sIjSNTS7Fs",
            ],
            (object) [
                "name" => "Psát od prvních řádků",
                "interpreter" => "A. L. Webber",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=uf35-Q74tdQ",
            ],
            (object) [
                "name" => "Slunečníce",
                "interpreter" => "Eman Nováček",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=G6JQhz_deWU",
            ],
            (object) [
                "name" => "Žabák",
                "interpreter" => "Václav Trojan",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZkGFqW7iZIQ",
            ],
            (object) [
                "name" => "Smíření",
                "interpreter" => "Petr Ulrych",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gbigns3JDOI",
            ],
            (object) [
                "name" => "Padam, Padam",
                "interpreter" => "Henry Contet",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Kya3c4WJZAk",
            ],
            (object) [
                "name" => "Milord",
                "interpreter" => "Georges Moustaki",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=vwe3CzWZ4Bg",
            ],
            (object) [
                "name" => "Non Je Ne Regrette Rien",
                "interpreter" => "Charles Dumont",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Q3Kvu6Kgp88",
            ],
            (object) [
                "name" => "Čardáš swing",
                "interpreter" => "Ferdinand Havlík",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=7motL4NlTZ8",
            ],
            (object) [
                "name" => "New York",
                "interpreter" => "John Kander",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EUrUfJW1JGk",
            ],
            (object) [
                "name" => "Dneska pojedem vlakem ven",
                "interpreter" => "Havrani",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=TjUl1LO1zWk",
            ],
            (object) [
                "name" => "Sing, Sing, Sing",
                "interpreter" => "Louis Prima",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=fhyhP_5VfKM",
            ],
            (object) [
                "name" => "Everything",
                "interpreter" => "Michael Bublé",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SPUJIbXN0WY",
            ],
            (object) [
                "name" => "Feeling Good",
                "interpreter" => "L. Bricusse",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Edwsf-8F3sI",
            ],
            (object) [
                "name" => "Tiger Rag",
                "interpreter" => "La Rocca",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rqo-AuSFaQg",
            ],
            (object) [
                "name" => "Summertime",
                "interpreter" => "George Gershwin",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=XivELBdxVRM",
            ],
            (object) [
                "name" => "It Had Better Be Tonight",
                "interpreter" => "Henry Manchini",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=p6KsEY0NIkE",
            ],
            (object) [
                "name" => "All I Want For Christmas Is You",
                "interpreter" => "Mariah Carey",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=yXQViqx6GMY",
            ],
            (object) [
                "name" => "Jen jedenkrát v roce",
                "interpreter" => "Jiří Zmožek",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=-Fxj_4x4x2E",
            ],
            (object) [
                "name" => "Každý má svůj sen",
                "interpreter" => "A. L. Webber",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=SZtgPBXkOCs",
            ],
            (object) [
                "name" => "Yakety Sax",
                "interpreter" => "Benny Hill",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=ZnHmskwqCCQ",
            ],
            (object) [
                "name" => "Hluboko, hluboko",
                "interpreter" => "Bert Kaempfert",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=4Wh7fvg_W8Q",
            ],
            (object) [
                "name" => "Už nikdy víc milovat nebudu",
                "interpreter" => "Karel Hála",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=wragKkh75K8",
            ],
            (object) [
                "name" => "Vím, že jsi se mnou",
                "interpreter" => "Karel Svoboda",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=j4GyDhIPd0I",
            ],
            (object) [
                "name" => "Hádej Matyldo",
                "interpreter" => "Australská lidová",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=K8ConPKzAeo",
            ],
            (object) [
                "name" => "White Christmas",
                "interpreter" => "Michael Bublé",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=8OsgqpnuizY",
            ],
            (object) [
                "name" => "You Needed Me",
                "interpreter" => "Randy Goodrum",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=IZNBjY7F4EM",
            ],
            (object) [
                "name" => "Save The Last Dance For Me",
                "interpreter" => "Mort Shuman",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://youtu.be/LAjfB0XfjkA?t=9s",
            ],
            (object) [
                "name" => "Bei mir bist du schön",
                "interpreter" => "Sholom Sekunda",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=gQHXR8h4woQ",
            ],
            (object) [
                "name" => "Memory",
                "interpreter" => "A. L. Webber",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=4-L6rEm0rnY",
            ],
            (object) [
                "name" => "Tequila",
                "interpreter" => "Chuck Rio",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=zkNsspRhIGE",
            ],
            (object) [
                "name" => "My Way",
                "interpreter" => "Paul Anka",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=uP_tMa7VliY",
            ],
            (object) [
                "name" => "Over The Rainbow",
                "interpreter" => "Harold Arlen",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rectLMhmkz8",
            ],
            (object) [
                "name" => "Etuda v E",
                "interpreter" => "F. Chopin",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=EmQBFLJAIcY",
            ],
            (object) [
                "name" => "Alexander's Ragtime Band",
                "interpreter" => "Irving Berlin",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=qPTbgvzgMZU",
            ],
            (object) [
                "name" => "Rock This Town",
                "interpreter" => "Brian Setzer",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mvs9ODIjhiU",
            ],
            (object) [
                "name" => "Yesterday",
                "interpreter" => "Paul McCartney",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://youtu.be/piBiR4vOBm0?t=18s",
            ],
            (object) [
                "name" => "Strangers In The Night",
                "interpreter" => "Frank Sinatra",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=hlSbSKNk9f0",
            ],
            (object) [
                "name" => "Blues Machine",
                "interpreter" => "Michael Sweeney",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=F7bqncyxrzA",
            ],
            (object) [
                "name" => "Thunderball",
                "interpreter" => "John Barry",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=xAQ-nG0AlSg",
            ],
            (object) [
                "name" => "Tenkrát na západě",
                "interpreter" => "Enrico Morricone",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=rJDVJy260yQ",
            ],
            (object) [
                "name" => "Beatles Hits",
                "interpreter" => "John Lennon",
                "duration" => NULL,
                "visible" => true,
                "link" => NULL,
            ],
            (object) [
                "name" => "Let It Snow",
                "interpreter" => "Jule Styne",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=mN7LW0Y00kE",
            ],
            (object) [
                "name" => "Monday Monday",
                "interpreter" => "John Phillips",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=h81Ojd3d2rY",
            ],
            (object) [
                "name" => "Funiculi Funicula",
                "interpreter" => "Luigi Denza",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=Guh_65i8jZk",
            ],
 
 
            (object) [
                "name" => "Jazz Merry Christmas",
                "interpreter" => "Paul Cook",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=CHTWL-7yD6w",
            ],
            (object) [
                "name" => "Somewhere",
                "interpreter" => "Leonard Bernstein",
                "duration" => NULL,
                "visible" => true,
                "link" => "https://www.youtube.com/watch?v=0gIoTnBlh2Q",
            ],
            (object) [
                "name" => "Četník ze Saint Tropez",
                "interpreter" => "Raymond Lefevre",
                "duration" => NULL,
                "visible" => true,
                "link" => "",
            ],
            (object) [
                "name" => "Četník v New Yorku",
                "interpreter" => "Raymond Lefevre",
                "duration" => NULL,
                "visible" => true,
                "link" => "",
            ],
		);
	}


	public function all ( $order = [] )
	{
		uasort($this->songs, function($a, $b) {
			return Nette\Utils\Strings::toAscii($a->name) > Nette\Utils\Strings::toAscii($b->name);
		});
		return $this->songs;
	}

	public function by ( $by = array (), $order = array () )
	{
		$order = array_keys($order)[0];
		uasort($this->songs, function($a, $b) use ($order) {
			return Nette\Utils\Strings::toAscii($a->$order) > Nette\Utils\Strings::toAscii($b->$order);
		});
		return $this->songs;
	}

};